title: dcHiChIP
description: "Nextflow-based pipeline for HiChIP analysis"
remote_theme: ELIXIR-Belgium/elixir-toolkit-theme

# GitHub Pages base
url: "https://sfglab.github.io"
baseurl: "/dcHiChIP"

# Top bar title (also used by the theme in various places)
topnav_title: dcHiChIP

# Theme options & branding
theme_variables:
  # --- BRANDING (logo at top-left) ---
  brand_logo: assets/UW-logo-hover.png   # <-- put the file at docs/assets/UW-logo-hover.png
  brand_name: dcHiChIP                   # remove this line if you want logo only (no text)

  # --- NAV / UI ---
  topnav:
    theme: light
    github: true

  # --- GitHub buttons (shown by the theme) ---
  github_buttons:
    position: bottom
    edit_me: true
    open_issue: true
    history: true

  # --- Table of contents behavior ---
  toc:
    min_headings: 1
    headings: 'main h2'

# Pretty URLs site-wide (keeps /page/ instead of .html; you can still override with page front matter)
permalink: pretty

# Default layout for all pages unless overridden
defaults:
  - scope:
      path: ""
    values:
      layout: default
